### ISSUE TITLE
Wrapping all responses by a DTO class in api layer

### ISSUE THREAD

**Issue by ali4j** [softwaretalks/jangul#21]
Dear Soroosh 
I feel that it is a good idea to have a DTO class (e.g ResponseDTO) to wrap all responses (both successful and failed ones) returned by the apis. In this way a unified structure is returned to the client and it will ease the parsing process in client side.
For example ResponseDTO class can have these fields:

```
public class ResponseDTO<T> {
    private String status;
    private String message;
    private T body;
    //getters and setter
}
```

**Comment by psycho-ir** [comment]
Although I agree with having a DTO for errors i.e `ErrorDTO, but I don't see any point to wrap other responses in a response DTO as in the status is retrievable from the http code and message is mostly just a description for that and just repeating them in responses makes the API less understandable and more error prone.

**Comment by ali4j** [comment]
That's OK.
